name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
    steps:
    - uses: earthly/actions-setup@v1
      with:
        version: v0.7.21
    - uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0
    - name: Put back the git branch into git (Earthly uses it for tagging)
      run: |
        branch=""
        if [ -n "$GITHUB_HEAD_REF" ]; then
          branch="$GITHUB_HEAD_REF"
        else
          branch="${GITHUB_REF##*/}"
        fi
        git checkout -b "$branch" || true

    - name: earthly +build
      run: earthly +build

    - name: Upload Build Output
      uses: actions/upload-artifact@v2
      with:
        name: output
        path: ${{github.workspace}}/output
